<h2>Add a meetup</h2><br>

<?php /** @var \Zend\Form\Form $form */ ?>
<?php $form = $this->form; ?>

<?= $this->form()->openTag($form); ?>
    <?= $this->formRow($form->get('title')); ?><br>
    <?= $this->formRow($form->get('description')); ?><br>
    <?= $this->formRow($form->get('start_date')); ?><br>
    <?= $this->formRow($form->get('end_date')); ?><br>

    <?= $this->formInput($form->get('submit')); ?>
<?= $this->form()->closeTag($form); ?>

