<h2>Add a meetup</h2><br>

<p class="btn btn-info"><a href="<?= $this->url('meetups/list'); ?>">All Meetups</a></p>
<hr>

<?php /** @var \Zend\Form\Form $ownerForm */ ?>
<?php $ownerForm = $this->ownerForm; ?>
<h3><span class="label label-default">If you want to register a new owner for your Meetup</span></h3>
<br>
<?= $this->form()->openTag($ownerForm); ?>
    <?= $this->formRow($ownerForm->get('firstname')); ?><br>
    <?= $this->formRow($ownerForm->get('lastname')); ?><br>
    <?= $this->formRow($ownerForm->get('biography')); ?><br>

    <?= $this->formInput($ownerForm->get('submit')); ?>
<?= $this->form()->closeTag($ownerForm); ?>

<hr>

<?php /** @var \Zend\Form\Form $meetupForm */ ?>
<?php $meetupForm = $this->meetupForm; ?>
<h3><span class="label label-default">Create your Meetup</span></h3>
<br>
<?= $this->form()->openTag($meetupForm); ?>
    <?= $this->formRow($meetupForm->get('owner')); ?><br>

    <?= $this->formRow($meetupForm->get('title')); ?><br>
    <?= $this->formRow($meetupForm->get('description')); ?><br>

    <?= $this->formLabel($meetupForm->get('start_date')); ?>
    <div class="input-group">
        <?php /** @var DateTime $demoDate */ ?>
        <?php $demoDate = new DateTime(); ?>
        <?= $this->formInput($meetupForm->get('start_date')); ?>
        <span class="input-group-addon" id="basic-addon2">ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span>
    </div>
    <?= $this->formElementErrors($meetupForm->get('start_date')); ?>

    <?= $this->formLabel($meetupForm->get('end_date')); ?>
    <div class="input-group">
        <?php $demoDate->add(new DateInterval('PT2H30M')); ?>
        <?= $this->formInput($meetupForm->get('end_date')); ?>
        <span class="input-group-addon" id="basic-addon2">ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span>
    </div><br>
    <?= $this->formElementErrors($meetupForm->get('end_date')); ?>

    <?= $this->formInput($meetupForm->get('submit')); ?>
<?= $this->form()->closeTag($meetupForm); ?>
