<h2><?= $this->meetup->getTitle() ?></h2><br>

<a href="<?= $this->url('meetups/update', ['meetupId' => $this->meetup->getId()]); ?>">Edit this meetup</a>

<p><a href="<?= $this->url('meetups/list'); ?>">Back to Meetups list</a></p>

<p><?= $this->meetup->getDescription(); ?></p>
<p>Beginning : <span><?= $this->meetup->getStartDate()->format(\Application\Service\MeetupService::DISPLAY_DATE_FORMAT); ?></span></p>
<p>End : <span><?= $this->meetup->getEndDate()->format( \Application\Service\MeetupService::DISPLAY_DATE_FORMAT); ?></span></p>

<hr>

<h4>Meetup owners</h4>
<?php /** @var \Application\Entity\Owner $owner */ ?>
<?php foreach ($this->meetup->getOwners() as $owner): ?>
<div>
    <p><?= $owner->getFullName(); ?></p>
    <p><?= $owner->getBiography(); ?></p>
</div>
<?php endforeach; ?>

<hr>

<h4>Meetup participants</h4>
<?php /** @var \Application\Entity\Participant $participant */ ?>
<?php foreach ($this->meetup->getParticipants() as $participant): ?>
<div>
    <p><?= $participant->getFullName(); ?></p>
    <p><?= $participant->getEmail(); ?></p>
</div>
<?php endforeach; ?>

