<h2><?= $this->meetup->getTitle() ?></h2><br>

<a class="btn btn-warning" href="<?= $this->url('meetups/update', ['meetupId' => $this->meetup->getId()]); ?>">Edit</a>
<a class="btn btn-info" href="<?= $this->url('meetups/list'); ?>">All Meetups</a>
<br><br>
<p><?= $this->meetup->getDescription(); ?></p>
<p><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <u>Start</u> : <span><?= $this->meetup->getStartDate()->format(\Application\Service\MeetupService::DISPLAY_DATE_FORMAT); ?></span></p>
<p><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <u>End</u> : <span><?= $this->meetup->getEndDate()->format( \Application\Service\MeetupService::DISPLAY_DATE_FORMAT); ?></span></p>

<hr>

<h4>Meetup owners</h4>
<?php /** @var \Application\Entity\Owner $owner */ ?>
<?php foreach ($this->meetup->getOwners() as $owner): ?>
<div>
    <p><?= $owner->getFullName(); ?></p>
    <p><?= $owner->getBiography(); ?></p>
</div>
<?php endforeach; ?>

<hr>

<h4>Meetup participants</h4>
<?php /** @var \Application\Entity\Participant $participant */ ?>
<?php foreach ($this->meetup->getParticipants() as $participant): ?>
<div>
    <p><?= $participant->getFullName(); ?></p>
    <p><?= $participant->getEmail(); ?></p>
</div>
<?php endforeach; ?>

