<h2>Edit the meetup : <?= $this->meetup->getTitle(); ?></h2><br>

<p><a href="<?= $this->url('meetups/delete', ['meetupId' => $this->meetup->getId()]); ?>">Delete</a></p>
<p><a href="<?= $this->url('meetups/list'); ?>">All Meetups</a></p>
<hr>

<?php /** @var \Zend\Form\Form $ownerForm */ ?>
<?php $ownerForm = $this->ownerForm; ?>
<h4>If you want to register a new owner for your Meetups</h4>
<?= $this->form()->openTag($ownerForm); ?>
    <?= $this->formRow($ownerForm->get('firstname')); ?><br>
    <?= $this->formRow($ownerForm->get('lastname')); ?><br>
    <?= $this->formRow($ownerForm->get('biography')); ?><br>

    <?= $this->formInput($ownerForm->get('submit')); ?>
<?= $this->form()->closeTag($ownerForm); ?>

<hr>

<?php /** @var \Zend\Form\Form $meetupForm */ ?>
<?php $meetupForm = $this->meetupForm; ?>

<?= $this->form()->openTag($meetupForm); ?>
    <h4>Add an additional owner to the meetup</h4><br>
    <?= $this->formRow($meetupForm->get('owner')); ?><br>
    <?= $this->formInput($meetupForm->get('submit')); ?><br>
    <hr>

    <h4>Edit the meetup information</h4><br>
    <?= $this->formRow($meetupForm->get('title')); ?><br>
    <?= $this->formRow($meetupForm->get('description')); ?><br>

    <?php /** @var DateTime $demoDate */ ?>
    <?php $demoDate = new DateTime(); ?>
    <?= $this->formRow($meetupForm->get('start_date')); ?>
    <span>ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span><br>
    <?php $demoDate->add(new DateInterval('PT2H30M')); ?>
    <?= $this->formRow($meetupForm->get('end_date')); ?>
    <span>ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span><br>

    <?= $this->formInput($meetupForm->get('submit')); ?>
<?= $this->form()->closeTag($meetupForm); ?>

<hr>

<h4>Meetup owners</h4>
<?php /** @var \Application\Entity\Owner $owner */ ?>
<?php foreach ($this->meetup->getOwners() as $owner): ?>
    <div>
        <a href="<?= $this->url('owners/delete', ['meetupId' => $this->meetup->getId(), 'ownerId' => $owner->getId()]); ?>">Delete</a>
        <p><?= $owner->getFullName(); ?></p>
        <p><?= $owner->getBiography(); ?></p>
    </div>
<?php endforeach; ?>

<hr>

<?php /** @var \Zend\Form\Form $participantForm */ ?>
<?php $participantForm = $this->participantForm; ?>
<h4>Add a participant to the meetup</h4>
<?= $this->form()->openTag($participantForm); ?>
    <?= $this->formRow($participantForm->get('participant_firstname')); ?><br>
    <?= $this->formRow($participantForm->get('participant_lastname')); ?><br>
    <?= $this->formRow($participantForm->get('participant_email')); ?><br>

    <?= $this->formInput($participantForm->get('submit')); ?>
<?= $this->form()->closeTag($participantForm); ?>

<hr>

<h4>Meetup participants</h4>
<?php /** @var \Application\Entity\Participant $participant */ ?>
<?php foreach ($this->meetup->getParticipants() as $participant): ?>
    <div>
        <a href="<?= $this->url('participants/delete', ['meetupId' => $this->meetup->getId(), 'participantId' => $participant->getId()]); ?>">Delete</a>
        <p><?= $participant->getFullName(); ?></p>
        <p><?= $participant->getEmail(); ?></p>
    </div>
<?php endforeach; ?>
