<h2>
    Edit the meetup : <a href="<?= $this->url('meetups/details', ['meetupId' => $meetup->getId()]); ?>"><?= $this->meetup->getTitle(); ?></a>
</h2><br>

<a class="btn btn-info" href="<?= $this->url('meetups/list'); ?>">All Meetups</a>
<a class="btn btn-danger" href="<?= $this->url('meetups/delete', ['meetupId' => $this->meetup->getId()]); ?>">Delete</a>
<hr>

<?php /** @var \Zend\Form\Form $ownerForm */ ?>
<?php $ownerForm = $this->ownerForm; ?>
<h3><span class="label label-default">If you want to register a new owner for your Meetups</span></h3>
<br>
<?= $this->form()->openTag($ownerForm); ?>
    <?= $this->formRow($ownerForm->get('firstname')); ?><br>
    <?= $this->formRow($ownerForm->get('lastname')); ?><br>
    <?= $this->formRow($ownerForm->get('biography')); ?><br>

    <?= $this->formInput($ownerForm->get('submit')); ?>
<?= $this->form()->closeTag($ownerForm); ?>

<hr>

<?php /** @var \Zend\Form\Form $meetupForm */ ?>
<?php $meetupForm = $this->meetupForm; ?>

<?= $this->form()->openTag($meetupForm); ?>
    <h3><span class="label label-default">Add an additional owner to the meetup</span></h3><br>
    <?= $this->formRow($meetupForm->get('owner')); ?><br>
    <?= $this->formInput($meetupForm->get('submit')); ?><br>
    <hr>

    <h3><span class="label label-default">Edit the meetup information</span></h3><br>
    <?= $this->formRow($meetupForm->get('title')); ?><br>
    <?= $this->formRow($meetupForm->get('description')); ?><br>

    <?= $this->formLabel($meetupForm->get('start_date')); ?>
    <div class="input-group">
        <?php /** @var DateTime $demoDate */ ?>
        <?php $demoDate = new DateTime(); ?>
        <?= $this->formInput($meetupForm->get('start_date')); ?>
        <span class="input-group-addon" id="basic-addon2">ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span>
    </div>
    <?= $this->formElementErrors($meetupForm->get('start_date')); ?>

    <?= $this->formLabel($meetupForm->get('end_date')); ?>
    <div class="input-group">
        <?php $demoDate->add(new DateInterval('PT2H30M')); ?>
        <?= $this->formInput($meetupForm->get('end_date')); ?>
        <span class="input-group-addon" id="basic-addon2">ex : <?= $demoDate->format(\Application\Form\MeetupForm::FORM_DATE_FORMAT); ?></span>
    </div><br>
    <?= $this->formElementErrors($meetupForm->get('end_date')); ?>

    <?= $this->formInput($meetupForm->get('submit')); ?>
<?= $this->form()->closeTag($meetupForm); ?>

<hr>

<h3><span class="label label-default">Meetup owners</span></h3>
<?php /** @var \Application\Entity\Owner $owner */ ?>
<?php foreach ($this->meetup->getOwners() as $owner): ?>
    <div>
        <a class="btn btn-danger" href="<?= $this->url('owners/delete', ['meetupId' => $this->meetup->getId(), 'ownerId' => $owner->getId()]); ?>">Delete</a>
        <p><?= $owner->getFullName(); ?></p>
        <p><?= $owner->getBiography(); ?></p>
    </div>
<?php endforeach; ?>

<hr>

<?php /** @var \Zend\Form\Form $participantForm */ ?>
<?php $participantForm = $this->participantForm; ?>
<h3><span class="label label-default">Add a participant to the meetup</span></h3>
<?= $this->form()->openTag($participantForm); ?>
    <?= $this->formRow($participantForm->get('participant_firstname')); ?><br>
    <?= $this->formRow($participantForm->get('participant_lastname')); ?><br>
    <?= $this->formRow($participantForm->get('participant_email')); ?><br>

    <?= $this->formInput($participantForm->get('submit')); ?>
<?= $this->form()->closeTag($participantForm); ?>

<hr>

<h3><span class="label label-default">Meetup participants</span></h3>
<?php /** @var \Application\Entity\Participant $participant */ ?>
<?php foreach ($this->meetup->getParticipants() as $participant): ?>
    <div>
        <a class="btn btn-danger" href="<?= $this->url('participants/delete', ['meetupId' => $this->meetup->getId(), 'participantId' => $participant->getId()]); ?>">Delete</a>
        <p><?= $participant->getFullName(); ?></p>
        <p><?= $participant->getEmail(); ?></p>
    </div>
<?php endforeach; ?>
